ASSETS="assets.go"

run: make-assets-go
	go fmt ./...
	go run *.go

compile-coffee:
	coffee -c assets/script.coffee

make-assets-go: compile-coffee
	echo "// Generated by Makefile" > $(ASSETS)
	echo "package main" >> $(ASSETS)
	echo "var assets = map[string]string {" >> $(ASSETS)

	for asset in assets/*; do\
		basename=$$(basename $$asset); \
		echo "\"$$basename\" : \`$$(cat $$asset)\`," >> $(ASSETS); \
	done

	echo "}" >> $(ASSETS)


