// This file is generated by Makefile
package codeiq

const Template = `
<!DOCTYPE html>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CodeIQ Answer Viewer</title>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<div class="container">

	<h1>CodeIQ Answer Viewer</h1>

	<div id="screens">
		<div id="screen-index">
			<form role="form" method="post" action="upload" enctype="multipart/form-data">
				<div class="form-group">
					<label for="exampleInputFile">CSVファイル</label>
					<input type="file" name="file" id="exampleInputFile" required>
				</div>
				<button type="submit" class="btn btn-default">アップロード</button>
			</form>

			<hr>

			<ul class="nav nav-tabs" id="filter-by-feedback">
				<li class="active"><a href="#" data-filter="all">すべて</a></li>
				<li><a href="#" data-filter="done">フィードバック済</a></li>
				<li><a href="#" data-filter="yet">フィードバック未</a></li>
			</ul>

			<table class="table table-striped" id="answer-table">
				<thead>
					<tr>
						<th>No</th>
						<th>挑戦者No</th>
						<th>挑戦回数</th>
						<th>ニックネーム</th>
						<th>性別</th>
						<th>年齢</th>
						<th>挑戦完了日時</th>
						<th>評価フィードバック済</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr id="answer-row">
						<td class="No">???</td>
						<td class="ChallengerNo">???</td>
						<td class="ChallengeCount">???</td>
						<td class="Nickname">???</td>
						<td class="Gender">???</td>
						<td class="Age">???</td>
						<td class="ChallengedOn">????年?月?日 ??:??</td>
						<td class="Feedbacked">??</td>
						<td><a href="#" class="detail" data-no="??">詳細</a></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div id="screen-detail">
			<ol class="breadcrumb">
				<li><a href="/">Top</a></li>
				<li class="active">詳細</li>
			</ol>

			<table class="table table-striped" id="detail-table">
				<thead>
					<tr>
						<th>No</th>
						<th>挑戦者No</th>
						<th>ニックネーム</th>
						<th>性別</th>
						<th>挑戦完了日時</th>
						<th>評価フィードバック済</th>
					</tr>
				</thead>
				<tbody>
					<tr id="answer-row">
						<td class="No">???</td>
						<td class="ChallengerNo">???</td>
						<td class="Nickname">???</td>
						<td class="Gender">???</td>
						<td class="ChallengedOn">????年?月?日 ??:??</td>
						<td class="Feedbacked">??</td>
					</tr>
				</tbody>
			</table>
			<p class="legend">解答テキスト</p>
			<pre class="AnswerText">package main

	import (
	    "fmt"
	)

	func main() {
	    fmt.Print("Hello World\n")
	}</pre>
		</div>
	</div>

	<hr>

	<div class="footer" style="margin-bottom:20px;">
		<div>CodeIQ Answer Viewer ver<span id="version">?.?.?</span> | Fork on GitHub</div>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

`
const Script = `
// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    var answerRowTemplate, initTemplates, linkDetail, main, renderAnswer, renderAnswers, setUpFilter, showScreen;
    $.get("/assets/template.html", function(template) {
      document.write(template);
      initTemplates();
      return main();
    });
    answerRowTemplate = void 0;
    initTemplates = function() {
      answerRowTemplate = $("#answer-row").clone();
      return $("#answer-table tbody *").remove();
    };
    main = function() {
      showScreen("screen-index");
      renderAnswers();
      setUpFilter();
      return linkDetail();
    };
    showScreen = function(id) {
      $("#screens > div").hide();
      return $("#" + id).show();
    };
    renderAnswers = function() {
      return $.get("/answers", function(answers) {
        return $(answers).each(function(index, answer) {
          var answerRow;
          answerRow = answerRowTemplate.clone();
          return answerRow.find(".No").text(answer.No).end().find(".ChallengerNo").text(answer.ChallengerNo).end().find(".ChallengeCount").text(answer.ChallengeCount).end().find(".Nickname").text(answer.Nickname).end().find(".Gender").text(answer.Gender).end().find(".Age").text(answer.Age).end().find(".ChallengedOn").text(answer.ChallengedOn).end().find(".Feedbacked").text(answer.Feedbacked).end().find("a.detail").attr("data-no", answer.No).end().attr("data-feedbacked", answer.Feedbacked).appendTo("#answer-table tbody");
        });
      });
    };
    renderAnswer = function(number) {
      return $.get("/answers/" + number).success(function(answer) {
        showScreen("screen-detail");
        return $("#screen-detail").find(".No").text(answer.No).end().find(".ChallengerNo").text(answer.ChallengerNo).end().find(".ChallengeCount").text(answer.ChallengeCount).end().find(".Nickname").text(answer.Nickname).end().find(".Gender").text(answer.Gender).end().find(".Age").text(answer.Age).end().find(".ChallengedOn").text(answer.ChallengedOn).end().find(".Feedbacked").text(answer.Feedbacked).end().find(".AnswerText").text(answer.AnswerText).end();
      }).error(function() {
        return alert("failed to load data");
      });
    };
    setUpFilter = function() {
      return $("#filter-by-feedback a").on("click", function() {
        var filterBy;
        filterBy = $(this).data("filter");
        $("#filter-by-feedback li").removeClass("active");
        $(this).parent().addClass("active");
        if (filterBy === "done") {
          $("#answer-table tbody tr:not([data-feedbacked=済])").hide();
          $("#answer-table tbody tr[data-feedbacked=済]").show();
          return false;
        }
        if (filterBy === "yet") {
          $("#answer-table tbody tr:not([data-feedbacked=未])").hide();
          $("#answer-table tbody tr[data-feedbacked=未]").show();
          return false;
        }
        $("#answer-table tbody tr").show();
        return false;
      });
    };
    return linkDetail = function() {
      return $(document).on("click", "a.detail", function() {
        renderAnswer($(this).data("no"));
        return false;
      });
    };
  });

}).call(this);
`
